### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by fabiooshiro** [Calindra/cartesify#1]
```
pnpm run deploy

> learn-erc-20@1.0.0 deploy /Users/oshiro/calindra/cartesi/cartesi-store/onchain
> hardhat run --network localhost scripts/deploy.js

Compiled 13 Solidity files successfully (evm target: london).
Deploying NonFunToken... 0
NonFunToken deployed to: 0xc6e7DF5E7b4f2A278906862b61205850344D4e7d
Mint NFT to 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
http://localhost:5173/carousel/0.json
Listando 0
Error POST http://127.0.0.1:8383/erc-721/list TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at $86549a80ad739fbb$var$doRequestWithAdvance (file:///Users/oshiro/calindra/cartesi/cartesi-store/onchain/node_modules/.pnpm/@calindra+cartesify@0.1.2/node_modules/@calindra/cartesify/src/cartesify/FetchLikeClient.ts:45:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

file:///Users/oshiro/calindra/cartesi/cartesi-store/onchain/node_modules/.pnpm/@calindra+cartesify@0.1.2/node_modules/@calindra/cartesify/src/cartesify/FetchLikeClient.ts:45
            JSON.stringify({
                 ^
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at $86549a80ad739fbb$var$doRequestWithAdvance (file:///Users/oshiro/calindra/cartesi/cartesi-store/onchain/node_modules/.pnpm/@calindra+cartesify@0.1.2/node_modules/@calindra/cartesify/src/cartesify/FetchLikeClient.ts:45:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by fabiooshiro** [comment]
fixed: v0.1.3
